AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - org.raduceaca::java-spring-on-lambda
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  JavaSpringOnLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.raduceaca.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  JavaSpringOnLambdaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: JavaSpringOnLambdaApi
